[book]
authors = ["Michael Carson", "Gavin Baker", "Jake Hamzawi"]
language = "en"
src = "src"
title = "Thorium"

[build]
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true
