# quickwit
quickwit_enabled: true
quickwit_helm_chart_version: "0.7.18"
quickwit_namespace: "quickwit"
quickwit_container_registry: "docker.io"
quickwit_image: "quickwit/quickwit"
quickwit_bucket: "quickwit"
quickwit_postgres_replicas: 1
quickwit_postgres_container_registry: "docker.io"
quickwit_postgres_image: "postgres"
quickwit_postgres_version: "17"
quickwit_postgres_host: "postgres.quickwit.svc.cluster.local.:5432"
quickwit_host: "http://quickwit-indexer.quickwit.svc.cluster.local:7281"
quickwit_metastore_replica_count: 1
quickwit_searcher_replica_count: 1
quickwit_postgress_storage_size: "32G"
quickwit_postgres_memory_requests: "1Gi"
quickwit_postgres_cpu_requests: "1"
quickwit_postgres_memory_limits: "2Gi"
quickwit_postgres_cpu_limits: "2"
