offline: false
use_proxy: false
service_wait_timeout: 300
resource_creation_timeout: 30
# storage_class: ceph-block # use with rook
# storage_class: hostpath # use with docker desktop k8s
storage_class: local-path
vault_password_file: "artifacts/vault_pass"
# vault_path: "artifacts/secrets.yml"

# Elastic
elastic_enabled: true
# elastic_namespace: "elastic-system"
# elastic_url: "https://elastic-es-http.elastic-system.svc.cluster.local:9200"
# elastic_username: "thorium"

# Redis
redis_enabled: true
# redis_namespace: "redis"
# redis_host: "redis.redis.svc.cluster.local"
# redis_port: 6379

# Minio
minio_enabled: false
# minio_namespace: "minio"

# Rook Operator
rook_enabled: true
rook_helm_chart_version: "v1.18.1"
# rook_namespace: "rook-ceph"

# Rook Ceph Cluster
ceph_ignore_health_errors: true
ceph_health_check_retries: 1

# S3
s3_endpoint: "http://minio.minio.svc.cluster.local"
# s3_endpoint: "http://rook-ceph-rgw-thorium-s3.rook-ceph.svc.cluster.local"
s3_region: "default" # default or thorium-s3 when using rook
s3_flavor: "minio" # leave s3 as minio for rook/ceph
s3_validate_certs: true

# Jaeger
jaeger_enabled: true
# jaeger_namespace: "jaeger"

# Kubegres
kubegres_enabled: true

# Quickwit
quickwit_enabled: true
quickwit_helm_chart_version: "0.7.18"
# quickwit_namespace: "quickwit"
# quickwit_postgres_host: "postgres.quickwit.svc.cluster.local.:5432"
# quickwit_host: "http://quickwit-indexer.quickwit.svc.cluster.local:7281"
quickwit_bucket: "quickwit"

# Traefik
traefik_enabled: true
traefik_helm_chart_version: "37.1.0"
# traefik_namespace: "traefik"

# Cert Manager
cert_manager_enabled: true

# Scylla:
scylla_enabled: true

# Scylla Operator
scylla_helm_chart_version: "v1.16.3"
# scylla_operator_namespace: "scylla-operator"

# Scylla Cluster
# scylla_username: "thorium"
# scylla_namespace: "scylla"
# scylla_nodes:
#   - "scylla-client.scylla.svc.cluster.local" 

# Thorium Operator
thorium_enabled: true
# thorium_deployment_name: "dev"
# thorium_namespace: "thorium"
# thorium_version: "latest"
# Pull secret value is just a stub placeholder base64(thorium:corn)
# thorium_image_pull_secret:
#   auths: 
#     "registry.domain:port":
#       "auth: "dGhvcml1bTpjb3JuCg=="
# thorium_ui_banner: |
#   Welcome to Thorium. <Please place you banner here>
#
# thorium_ingress_hostname: "*" # or put thorium.<SLD>.<TLD>
# thorium_tls_cert_secret_name: "api-certs
